// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkniezdlyrmdzhytzrsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrbmllemRseXJtZHpoeXR6cnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNTMyMTcsImV4cCI6MjA4ODkyOTIxN30.qk64JwD4WCTfEshcFyhsvBd-j6l1vNOx5g-S7X0Xna0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});